wireguard: arbitrary interface names support
gentoo/netifrc pull request #40
Opened 2021-09-28 14:31 UTC by volkov-am

Arbitrary interface names are useful in case of wireguard interface groups covered by different iptables wildcard matches.

2023-11-25 04:59 UTC, robbat2 commented
Please rebase

2023-11-25 04:59 UTC, robbat2 requested changes
rebase needed

2024-05-23 16:05 UTC, chutz commented
This looks good to me, however please amend your commits to add a certificate of origin:
https://devmanual.gentoo.org/general-concepts/copyright-policy/index.html#certificate-of-origin

2024-05-24 05:56 UTC, volkov-am commented
signed-off, rebased one more time

2024-06-11 00:39 UTC, merged